version: "3"
services:
  app:
    image: stores_app:latest
    networks:
      postgres-demo:
    container_name: app
    expose:
      - 8081
    ports:
      - 8081:8081
    restart: on-failure
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:latest
    networks:
      postgres-demo:
    expose:
      - 5434
    ports:
      - 5434:5434
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stores
    restart: always
networks:
  postgres-demo:
